0:
	gcc -Wall -Wextra -Werror -pedantic 0-main.c 0-linear.c -g -o 0-linear
0r: 0
	./0-liner
1:
	gcc -Wall -Wextra -Werror -pedantic 1-main.c 1-binary.c -o 1-binary
1r: 1
	./1-binary
100:
	gcc -Wall -Wextra -Werror -pedantic 100-main.c 100-jump.c -lm -o 100-jump
100r: 100
	./100-jump
102:
	gcc -Wall -Wextra -Werror -pedantic 102-main.c 102-interpolation.c -o 102-interpolation
102r: 102
	./102-interpolation
103:
	gcc -Wall -Wextra -Werror -pedantic 103-main.c 103-exponential.c -o 103-exponential
103r: 103
	./103-exponential
104:
	gcc -Wall -Wextra -Werror -pedantic 104-main.c 104-advanced_binary.c -o 104-advanced_binary
104r: 104
	./104-advanced_binary
